//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.String {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R.String.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message(s) delete successfully!.
        /// </summary>
        public static string SuccessDeleteMessages {
            get {
                return ResourceManager.GetString("SuccessDeleteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend added successfully!.
        /// </summary>
        public static string SuccessFriendAdd {
            get {
                return ResourceManager.GetString("SuccessFriendAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend removed successfully!.
        /// </summary>
        public static string SuccessFriendRemove {
            get {
                return ResourceManager.GetString("SuccessFriendRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully!.
        /// </summary>
        public static string SuccessMessageSent {
            get {
                return ResourceManager.GetString("SuccessMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update save successfully!.
        /// </summary>
        public static string SuccessProfileUpdate {
            get {
                return ResourceManager.GetString("SuccessProfileUpdate", resourceCulture);
            }
        }
    }
}
